---  
  - name: "install node exporter binaries"
    become: true
    shell: |
      wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
      tar xvfz node_exporter-1.3.1.linux-amd64.tar.gz
      pwd
      ls -a
      cd node_exporter-1.3.1.linux-amd64 && ls -a

  # - name: "install node exporter binaries"
  #   become: true
  #   shell: |      
  #     wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
  #     tar xvfz node_exporter-1.3.1.linux-amd64.tar.gz
  #     cd node_exporter-1.3.1.linux-amd64 && ./node_exporter
