---  
  # - name: "install server binaries and configure"
  #   become: true
  #   shell: |      
  #     wget https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz
  #     tar xvfz prometheus-2.37.0.linux-amd64.tar.gz
  #     pwd
  #     ls -a
  #     cd prometheus-2.37.0.linux-amd64 && ls -a

  - name: "install server binaries and configure"
    become: true
    shell: |      
      wget https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz
      tar xvfz prometheus-2.37.0.linux-amd64.tar.gz
      cd prometheus-2.37.0.linux-amd64
      ~/prometheus --config.file=~/prometheus.yml
